# Generated by Django 4.1.6 on 2023-04-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_remove_user_ultimo_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(default='', max_length=45, unique=True),
        ),
    ]
