# Generated by Django 4.1.6 on 2023-03-22 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entregas', '0003_itementrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.item', verbose_name='Item movido')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='estoque.movimentacao')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
    ]
