# Generated by Django 4.1.6 on 2023-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_movimentacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
