# Generated by Django 4.1.6 on 2023-03-14 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='componenteFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=200)),
                ('cpf', models.CharField(default=None, max_length=45, verbose_name='CPF')),
                ('rg', models.CharField(default=None, max_length=45, verbose_name='RG')),
                ('papel', models.CharField(choices=[('PAI', 'Pai'), ('MÃE', 'Mãe'), ('FILHO/FILHA', 'Filho/Filha')], default='PAI', max_length=11)),
                ('nascimento', models.DateField(default=None)),
                ('NR_calcado', models.CharField(max_length=50)),
                ('NR_roupa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Integrante de Família',
                'verbose_name_plural': 'Integrantes de Família',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=200)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('unidade_federativa', models.CharField(max_length=2)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('celular', models.CharField(max_length=45)),
                ('moradia', models.CharField(max_length=45)),
                ('casa_de', models.CharField(max_length=45)),
                ('condicoes_casa', models.CharField(max_length=45)),
                ('aluguel', models.DecimalField(decimal_places=2, max_digits=20)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('realizado_por', models.CharField(max_length=100)),
                ('observacao', models.TextField()),
                ('componentes', models.ManyToManyField(to='familias.componentefamilia', verbose_name='Composição')),
            ],
        ),
    ]
