# Generated by Django 4.1.6 on 2023-03-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_renda', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familias.familia', verbose_name='Renda da Familia')),
            ],
        ),
    ]
