# Generated by Django 4.1.6 on 2023-03-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0002_rendafamiliar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendafamiliar',
            options={'verbose_name': 'Renda da Familia', 'verbose_name_plural': 'Rendas das Familias'},
        ),
        migrations.AlterField(
            model_name='componentefamilia',
            name='papel',
            field=models.CharField(choices=[('p', 'Pai'), ('m', 'Mãe'), ('f', 'Filho/Filha')], default='Pai', max_length=11),
        ),
    ]
