# Generated by Django 4.1.6 on 2023-03-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0003_alter_rendafamiliar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentefamilia',
            name='papel',
            field=models.CharField(choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Filho/Filha', 'Filho/Filha')], default='Pai', max_length=11),
        ),
    ]
