# Generated by Django 3.2.9 on 2023-03-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0004_alter_componentefamilia_papel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='nome',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
