# Generated by Django 3.2.9 on 2023-04-26 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0005_alter_familia_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendafamiliar',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
