# Generated by Django 4.1.6 on 2023-05-05 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0006_alter_rendafamiliar_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rendafamiliar',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
