# Generated by Django 4.1.6 on 2023-05-05 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0007_alter_familia_aluguel_alter_rendafamiliar_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
