# Generated by Django 4.1.6 on 2023-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0008_alter_familia_aluguel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='moradia',
            field=models.CharField(choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Filho/Filha', 'Filho/Filha')], default='Casa', max_length=45),
        ),
    ]
