# Generated by Django 4.1.6 on 2023-03-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familias', '0004_alter_componentefamilia_papel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=None)),
                ('pedidos', models.TextField()),
                ('observacao', models.TextField()),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familias.familia', verbose_name='Visita para a Familia')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
    ]
