# Generated by Django 4.1.6 on 2023-03-17 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaParticipantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Participantes da Visita')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitas.visita', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Participantes Visita',
                'verbose_name_plural': 'Participantes visita',
            },
        ),
    ]
