# Generated by Django 3.2.9 on 2023-03-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('unidade', models.CharField(max_length=45)),
                ('multiplicador', models.DecimalField(decimal_places=2, max_digits=20)),
                ('codigo_barras', models.CharField(max_length=100)),
                ('estoque_atual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('observacao', models.TextField()),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
