# Generated by Django 3.2.9 on 2023-03-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.entrega', verbose_name='Entrega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.item', verbose_name='Item da entrega')),
            ],
            options={
                'verbose_name': 'Item da entrega',
                'verbose_name_plural': 'Itens de entregas',
            },
        ),
    ]
