# Generated by Django 3.2.9 on 2023-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_itementrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unidade',
            field=models.FloatField(db_column='calculo_unidade', default=0, editable=False),
        ),
    ]
