# Generated by Django 4.1.6 on 2023-04-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0005_alter_item_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itementrega',
            name='quantidade',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
