# Generated by Django 4.1.6 on 2023-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=200)),
                ('celular', models.CharField(max_length=45)),
                ('bairro', models.CharField(max_length=200)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=200)),
                ('unidade_federativa', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Doador',
                'verbose_name_plural': 'Doadores',
            },
        ),
    ]
