# Generated by Django 4.1.6 on 2023-03-22 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_doacao', models.DateField(default=None)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.doador', verbose_name='Doador')),
            ],
            options={
                'verbose_name': 'Doações',
                'verbose_name_plural': 'Doações',
            },
        ),
    ]
