# Generated by Django 4.1.6 on 2023-03-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_itementrega'),
        ('doacoes', '0002_doacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacoes.doacao', verbose_name='Doação')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.item', verbose_name='Item da doação')),
            ],
            options={
                'verbose_name': 'Item da doação',
                'verbose_name_plural': 'Itens de doações',
            },
        ),
    ]
