# Generated by Django 4.1.6 on 2023-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0003_itemdoacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdoacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
