# Generated by Django 3.2.9 on 2023-04-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0004_alter_itemdoacao_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='data_doacao',
            field=models.DateTimeField(default=None),
        ),
    ]
